# YouTube Subtitle Explorer
# 
# @author  Jasper Palfree <jasper@wellcaffeinated.net>
# @copyright 2012 Jasper Palfree
# @license http:#opensource.org/licenses/mit-license.php MIT License

# uncomment to activate debug mode
# debug: true

ytse.config:
    # path to create sqlite database
    db.path: %ytse.root%/app/db/ytse.db

# YouTube API Key
api.config:
    yt.api.key: YOUR_DEVELOPER_KEY

# Youtube Playlist to use
ytplaylist.config:
    playlist: YOUR_PLAYLIST_ID
    lang_file: %ytse.root%/app/db/languages.csv
    # the default language code to highlight
    default_lang: en

# Google App OAuth consumer key and secret and admin youtube username
oauth.config:
    provider: google
    key: YOUR_CLIENT_ID
    secret: YOUR_CLIENT_SECRET
    admin: YOUR_YOUTUBE_USERNAME

# location of caption uploads
captions.config:
    caption_dir: %ytse.root%/app/uploads
