# YouTube Subtitle Explorer
# 
# @author  Jasper Palfree <jasper@wellcaffeinated.net>
# @copyright 2012 Jasper Palfree
# @license http://opensource.org/licenses/mit-license.php MIT License

# uncomment to activate debug mode
# debug: true

ytse.config:
    # path to create sqlite database
    db.path: %ytse.root%/user/db/ytse.db
    # list of email addresses to notify about new submissions
    email_notify: # [ 'example@example.com', 'ex2@...' ]
    email_from: no-reply@example.com

swiftmailer.options:
    host: localhost
    port: 25
    username: ''
    password: ''
    auth_mode: false

# YouTube API Key
api.config:
    yt.api.key: YOUR_DEVELOPER_KEY
    # type of thumbnail image to use
    thumbnail: mqdefault

# Youtube Playlist to use
ytplaylist.config:
    playlist: YOUR_PLAYLIST_ID
    orderby: position
    direction: desc
    lang_file: %ytse.root%/app/data/languages.csv
    # the default language code to highlight
    default_lang: en

# Google App OAuth consumer key and secret and admin youtube username
oauth.config:
    provider: google
    key: YOUR_CLIENT_ID
    secret: YOUR_CLIENT_SECRET
    admin: YOUR_YOUTUBE_USERNAME

# location of caption uploads
captions.config:
    caption_dir: %ytse.root%/user/uploads
